
llm_provider: "openai"
api_key: "your-api-key-here"  # Replace with your OpenAI API key
model: "gpt-4"               # Alternatives: "gpt-3.5-turbo", "gpt-4-turbo"
temperature: 0.7             # Controls randomness (0.0 to 1.0)
max_tokens: 2048             # Maximum length of responses